export const NON_PUNCTUATED_INTERROGATIVE_LEADING_WORDS = new Set([
  "aren't",
  'are',
  "can't",
  'can',
  'cannot',
  "couldn't",
  'could',
  "didn't",
  'did',
  "doesn't",
  'does',
  "hadn't",
  'had',
  "haven't",
  "hasn't",
  'has',
  'how',
  "isn't",
  'is',
  'may',
  "mayn't",
  'might',
  "mightn't",
  'must',
  "mustn't",
  "needn't",
  'ought',
  "oughtn't",
  "shan't",
  'shall',
  "shouldn't",
  'should',
  "wasn't",
  'was',
  "weren't",
  'were',
  'when',
  'where',
  'what',
  'which',
  'who',
  'whom',
  'whose',
  'why',
  "won't",
  'will',
  "wouldn't",
  'would',
])

export const CONTEXTUAL_NON_PUNCTUATED_INTERROGATIVE_LEADING_WORDS = new Set([
  'am',
  "don't",
  'do',
  'have',
  'need',
])

export const NON_PUNCTUATED_INTERROGATIVE_WH_LEADING_WORDS = new Set([
  'how',
  'what',
  'when',
  'where',
  'which',
  'who',
  'whom',
  'whose',
  'why',
])

export const NON_PUNCTUATED_INTERROGATIVE_ADVERB_LEADING_WORDS = new Set(['how', 'when', 'where', 'why'])

export const NON_PUNCTUATED_INTERROGATIVE_AUXILIARY_TOKENS = new Set([
  'am',
  "aren't",
  'are',
  'be',
  'been',
  'being',
  "can't",
  'can',
  'cannot',
  "couldn't",
  'could',
  "didn't",
  'did',
  'do',
  "doesn't",
  'does',
  "hadn't",
  'had',
  "haven't",
  "hasn't",
  'has',
  'have',
  "isn't",
  'is',
  'may',
  "mayn't",
  'might',
  "mightn't",
  'must',
  "mustn't",
  "needn't",
  'ought',
  "oughtn't",
  "shan't",
  'shall',
  "shouldn't",
  'should',
  "wasn't",
  'was',
  "weren't",
  'were',
  "won't",
  'will',
  "wouldn't",
  'would',
])

export const NON_PUNCTUATED_INTERROGATIVE_COPULA_TOKENS = new Set([
  'am',
  'are',
  'be',
  'been',
  'being',
  'is',
  'was',
  'were',
])

export const NON_PUNCTUATED_INTERROGATIVE_LINKING_PREDICATE_TOKENS = new Set([
  'remain',
  'remained',
  'remains',
  'stay',
  'stayed',
  'stays',
])

export const NON_PUNCTUATED_INTERROGATIVE_AUXILIARY_LEXICAL_PREDICATE_TOKENS = new Set([
  'be',
  'been',
  'being',
  'do',
  'does',
  'did',
  'have',
  'has',
  'had',
])

export const NON_PUNCTUATED_INTERROGATIVE_HOW_QUESTION_SECOND_WORDS = new Set([
  'far',
  'few',
  'little',
  'long',
  'many',
  'much',
  'often',
  'soon',
])

export const NON_PUNCTUATED_INTERROGATIVE_HOW_EMBEDDED_CLAUSE_SECOND_WORDS = new Set([
  'far',
  'few',
  'little',
  'long',
  'many',
  'much',
  'often',
  'soon',
])

export const CONTEXTUAL_NON_PUNCTUATED_INTERROGATIVE_SUBJECT_WORDS = new Set([
  'a',
  'an',
  'he',
  'her',
  'his',
  'i',
  'it',
  'its',
  'my',
  'our',
  'she',
  'that',
  'their',
  'the',
  'these',
  'they',
  'this',
  'those',
  'we',
  'you',
  'your',
])

export const NON_PUNCTUATED_INTERROGATIVE_PREDICATE_FILLER_WORDS = new Set([
  'already',
  'also',
  'actually',
  'basically',
  'certainly',
  'clearly',
  'conceivably',
  'currently',
  'definitely',
  'effectively',
  'even',
  'essentially',
  'ever',
  'generally',
  'just',
  'largely',
  'maybe',
  'merely',
  'mostly',
  'not',
  'now',
  'obviously',
  'only',
  'perhaps',
  'plainly',
  'possibly',
  'presumably',
  'probably',
  'really',
  'simply',
  'strictly',
  'surely',
  'still',
  'then',
  'today',
  'virtually',
  'yet',
])

export const NON_PUNCTUATED_INTERROGATIVE_PREDICATE_FILLER_TOKEN_SEQUENCES = [
  ['a', 'bit'],
  ['a', 'fair', 'bit'],
  ['a', 'good', 'deal'],
  ['a', 'great', 'deal'],
  ['a', 'little'],
  ['a', 'little', 'bit'],
  ['a', 'lot'],
  ['a', 'whole', 'lot'],
  ['all', 'the', 'more'],
  ['all', 'too'],
  ['any', 'longer'],
  ['any', 'more'],
  ['at', 'the', 'least'],
  ['at', 'the', 'very', 'least'],
  ['by', 'now'],
  ['just', 'about'],
  ['just', 'plain'],
  ['kind', 'of'],
  ['less', 'and', 'less'],
  ['more', 'or', 'less'],
  ['more', 'and', 'more'],
  ['no', 'longer'],
  ['no', 'more'],
  ['sort', 'of'],
  ['at', 'all'],
  ['at', 'least'],
  ['at', 'most'],
  ['way', 'less'],
  ['way', 'more'],
] as const

export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_PREDICATE_LOOKAHEAD = 5
export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_SUPPORT_CHAIN_LOOKBACK = 10

export const NON_PUNCTUATED_INTERROGATIVE_NON_PREDICATE_WORDS = new Set([
  'a',
  'an',
  'and',
  'as',
  'at',
  'because',
  'before',
  'but',
  'by',
  'for',
  'from',
  'if',
  'in',
  'into',
  'of',
  'on',
  'onto',
  'or',
  'so',
  'than',
  'that',
  'the',
  'these',
  'this',
  'those',
  'to',
  'under',
  'until',
  'when',
  'where',
  'while',
  'with',
  'without',
])

export const CONTEXTUAL_BARE_HAVE_PARTICIPLE_PREDICATE_WORDS = new Set([
  'become',
  'been',
  'begun',
  'broken',
  'built',
  'come',
  'done',
  'drawn',
  'driven',
  'fallen',
  'felt',
  'found',
  'gone',
  'grown',
  'held',
  'kept',
  'known',
  'left',
  'lost',
  'made',
  'met',
  'put',
  'read',
  'run',
  'said',
  'seen',
  'sent',
  'set',
  'shown',
  'spent',
  'stood',
  'taken',
  'told',
  'understood',
  'won',
  'written',
])

export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_SUPPORT_TOKENS = new Set([
  'appear',
  'appeared',
  'appears',
  'continue',
  'continued',
  'continues',
  'come',
  'came',
  'comes',
  'grow',
  'grew',
  'grows',
  'get',
  'gets',
  'got',
  'happen',
  'happened',
  'happens',
  'need',
  'needed',
  'needs',
  'prove',
  'proved',
  'proves',
  'remain',
  'remained',
  'remains',
  'seem',
  'seemed',
  'seems',
  'tend',
  'tended',
  'tends',
  'used',
])

export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_COPULAR_SUPPORT_TOKENS = new Set([
  'apt',
  'bound',
  'certain',
  'due',
  'liable',
  'likely',
  'meant',
  'ready',
  'set',
  'sure',
  'unlikely',
])

export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_COPULAR_SUPPORT_MODIFIER_TOKENS = new Set([
  'almost',
  'extremely',
  'far',
  'fairly',
  'highly',
  'least',
  'less',
  'more',
  'most',
  'much',
  'nearly',
  'quite',
  'rather',
  'somewhat',
  'too',
  'very',
])

export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_NEGATIVE_COPULA_TOKENS = new Set([
  "aren't",
  "isn't",
  "wasn't",
  "weren't",
])

export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_TERMINAL_COPULA_LOOKBACK = 10

export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_PHRASAL_SUPPORT_TOKENS = new Set([
  'turn',
  'turned',
  'turns',
])

export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_CONTRACTED_STARTER_TOKENS = new Set([
  "there'd",
  "there'll",
  "there've",
])

export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_CONTRACTED_COPULA_TOKENS = new Set([
  "there's",
  "there're",
])

export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_BEING_SUPPORT_TOKENS = new Set([
  'keep',
  'keeps',
  'kept',
  'stop',
  'stopped',
  'stops',
])

export const NON_PUNCTUATED_INTERROGATIVE_EXISTENTIAL_BEING_PHRASAL_SUPPORT_CHAINS = [
  {
    verbs: new Set(['end', 'ended', 'ends']),
    particle: 'up',
  },
  {
    verbs: new Set(['go', 'goes', 'went']),
    particle: 'on',
  },
  {
    verbs: new Set(['wind', 'winds', 'wound']),
    particle: 'up',
  },
] as const

