import {
  buildDecisionPendingAnswerSourceConsumerDescriptor,
  buildPlanningPendingAnswerSourceConsumerDescriptor,
  resolveRemainingMatchingDecisionAnswerSourceGroupDescriptor,
  resolveRemainingMatchingPlanningAnswerSourceGroupDescriptor,
} from './answerInterpretationAnswerSourceSupport'
import { createAnswerInterpretationAnswerContentSupport } from './answerInterpretationAnswerContentSupport'
import { createAnswerInterpretationAuthorityRuntimeSupport } from './answerInterpretationAuthorityRuntimeSupport'
import { createAnswerInterpretationAutoProbeSupport } from './answerInterpretationAutoProbeSupport'
import { createAnswerInterpretationContentResolutionSupport } from './answerInterpretationContentResolutionSupport'
import { createAnswerInterpretationDecisionMaterializationSupport } from './answerInterpretationDecisionMaterializationSupport'
import { createAnswerInterpretationDecisionTopicSurfaceSupport } from './answerInterpretationDecisionTopicSurfaceSupport'
import { createDirectSourceResponseCompletenessSupport } from './answerInterpretationDirectCompletenessSupport'
import { AnswerInterpretationError } from './answerInterpretationErrors'
import {
  AutoSourceResponseTerminalError,
  createAnswerInterpretationFormatSupport,
} from './answerInterpretationFormatSupport'
import { createAnswerInterpretationMatchingRunSupport } from './answerInterpretationMatchingRunSupport'
import { createAnswerInterpretationOpenDecisionMaterializationSupport } from './answerInterpretationOpenDecisionMaterializationSupport'
import { createOpenDecisionSurfaceNoMatchSupport } from './answerInterpretationOpenDecisionSupport'
import { createAnswerInterpretationOrderedPendingSourceSupport } from './answerInterpretationOrderedPendingSourceSupport'
import { createAnswerInterpretationPlanningMaterializationSupport } from './answerInterpretationPlanningMaterializationSupport'
import type {
  InterpretableKnownDecision,
  InterpretableOpenDecision,
  InterpretablePlanningAnswer,
  MaterializedInterpretedDecisionAnswer,
} from './answerInterpretationPublicTypes'
import { createAnswerInterpretationQuestionRuntimeSupport } from './answerInterpretationQuestionRuntimeSupport'
import { createAnswerInterpretationRemainingDecisionAnswerSourceSupport } from './answerInterpretationRemainingDecisionAnswerSourceSupport'
import { createAnswerInterpretationRemainingPlanningSurfaceSupport } from './answerInterpretationRemainingPlanningSurfaceSupport'
import { createAnswerInterpretationReservedSourceMatchSupport } from './answerInterpretationReservedSourceMatchSupport'
import { createAnswerInterpretationSourceResponseSectionSupport } from './answerInterpretationSourceResponseSectionSupport'
import { createInterpretedSourceResponseState } from './answerInterpretationStateSupport'
import { SUBORDINATE_CLAUSE_LEADING_WORDS } from './answerInterpretationSubordinateClauseLexicon'
import {
  matchLeadingSubordinateClauseSequenceLength,
  sourceResponseStartsWithProtectedLeadingConjunctionSequence,
  startsWithMultiTokenSubordinateClauseSequence,
} from './answerInterpretationSubordinateClauseSupport'
import { createAnswerInterpretationTextUnitSupport } from './answerInterpretationTextUnitSupport'
import { createAnswerInterpretationTopicSourceSupport } from './answerInterpretationTopicSourceSupport'
import { createAnswerInterpretationTopicSourceResponseSectionSupport } from './answerInterpretationTopicSourceResponseSectionSupport'
import {
  buildDecisionAnswerSourceResponseCandidates,
  buildKnownDecisionSourceResponseCandidates,
  buildMatchingRunCandidateGroupKey,
  buildOpenDecisionSourceResponseCandidates,
  buildPlanningAnswerSourceResponseCandidates,
  dedupeNonEmptyStrings,
} from './answerInterpretationStrings'

export { AnswerInterpretationError }
export { createInterpretedSourceResponseState } from './answerInterpretationStateSupport'
export { INTERPRETABLE_SOURCE_RESPONSE_FORMATS } from './answerInterpretationTypes'
export type {
  InterpretableAnswerSource,
  InterpretableDecisionAnswerEntryInput,
  InterpretableDecisionFollowThroughInput,
  InterpretableKnownDecision,
  InterpretableOpenDecision,
  InterpretablePlanningAnswer,
  MaterializedInterpretedDecisionAnswer,
} from './answerInterpretationPublicTypes'

const TOPIC_SUMMARY_VERB_PATTERN =
  '(?:should|will|must|can|could|would|is|are|was|were|uses|use|means|requires|starts)'
const TOPIC_SUMMARY_PREFIX_PATTERN = '(?:for|about|regarding|on)'

const {
  isStandalonePresentationListMarker,
  normalizeExplicitTopicOrQuestionUnitText,
  normalizeGenericPendingOrMatchingUnitText,
  parseGenericPendingSourceResponseClauses,
  parseGenericPendingSourceResponseParagraphs,
  parseGenericPendingSourceResponseSentences,
  parsePendingSourceResponseConjunctions,
  parseTopicSourceResponseClauses,
  parseTopicSourceResponseParagraphs,
  parseTopicSourceResponseSentences,
  stripLeadingPresentationListMarkers,
  stripStandalonePresentationListMarkerTokens,
  stripTrailingPresentationListMarkers,
} = createAnswerInterpretationTextUnitSupport({
  sourceResponseStartsWithProtectedLeadingConjunctionSequence,
})

let extractExplicitTopicSummariesFromQuestionAnswerTextRef:
  | ((answer: string) => string[])
  | undefined
let extractIncompleteLeadingTopicAuthoritySummariesFromQuestionAnswerTextRef:
  | ((answer: string) => string[])
  | undefined
let extractIncompleteLeadingTopicAuthoritySummaryRef:
  | ((text: string) => string | undefined)
  | undefined

const {
  assertQuestionAnswerTopicAuthorityMatchesQuestion,
  assertTopicTextHasSubstantiveLeadingAnswerContent,
  extractAsTopicSummary,
  extractCopularTopicSummary,
  extractInferredTopicSummaries,
  extractLeadingTopicSummary,
  extractPrefixedTopicSummary,
  extractQuestionAuthorityTextsFromText,
  extractTopicAnchorCandidateSummariesFromText,
  extractTrailingTopicSummary,
  findMatchingNormalizedTopicLabels,
  findMatchingQuestionBlockIndexes,
  findMatchingQuestionClosingBlockIndexes,
  findMatchingQuestionClosingSpanIndexes,
  findMatchingQuestionSpanIndexes,
  findMatchingTopicBlockIndexes,
  findMatchingTopicClauseIndexes,
  findMatchingTopicClosingBlockIndexes,
  findMatchingTopicClosingSpanIndexes,
  findMatchingTopicParagraphIndexes,
  findMatchingTopicSentenceIndexes,
  findMatchingTopicSpanIndexes,
  findMatchingTopicTextUnitIndexes,
  normalizeQuestionPromptCore,
  resolveSingleTopicAnchorLabel,
  formatQuotedValueList,
  hasMultipleStableMatchHints,
  hasNonPunctuatedWhCommaContinuation,
  inferComparableExplicitLabelSummary,
  inferEmbeddedClosingTopicCandidateLabels,
  inferEmbeddedLeadingTopicCandidateLabels,
  inferSummaryFromDecisionKey,
  inferSummaryFromQuestionLabel,
  inferSummaryFromStableAnswerSourceKey,
  inferSummaryFromStableMatchHints,
  inferSummaryFromStablePrompt,
  inferSummaryFromStableSummaryKey,
  inferSummaryKeyFromStableAnswerSourceKey,
  inferTopicBlockAnchorLabelsFromParagraph,
  inferTopicClosingBlockLabelsFromParagraph,
  inferTopicClosingSpanLabelsFromSentence,
  inferTopicSpanAnchorLabelsFromSentence,
  inferTopicSummaryFromTopicBlock,
  inferTopicSummaryFromTopicClosingBlock,
  inferTopicSummaryFromTopicClosingSpan,
  inferTopicSummaryFromTopicParagraph,
  inferTopicSummaryFromTopicSentence,
  inferTopicSummaryFromTopicSpan,
  isQuestionSourceResponseText,
  matchLeadingTopicAuthority,
  normalizeEmbeddedMatchingRunText,
  normalizeExtractedTopicSummary,
  normalizeQuestionSourceResponsePrompt,
  paragraphTextImpliesMultipleTopicSummaries,
  parseQuestionSourceResponseBlocks,
  parseQuestionSourceResponseClauses,
  parseQuestionSourceResponseClosingBlocks,
  parseQuestionSourceResponseClosingSpans,
  parseQuestionSourceResponseMiddleBlocks,
  parseQuestionSourceResponseMiddleSpans,
  parseQuestionSourceResponseSpans,
  parseRequiredQuestionSourceResponseBlocks,
  parseRequiredQuestionSourceResponseClauses,
  parseRequiredQuestionSourceResponseClosingBlocks,
  parseRequiredQuestionSourceResponseClosingSpans,
  parseRequiredQuestionSourceResponseMiddleBlocks,
  parseRequiredQuestionSourceResponseMiddleSpans,
  parseRequiredQuestionSourceResponseSpans,
  registerMatchingRunCandidateGroups,
  registerQuestionAnchorCandidateGroups,
  registerTopicAnchorCandidates,
  resolveCanonicalQuestionAnchorMatch,
  resolveEmbeddedMatchingRunAnchors,
  resolveEmbeddedTopicAnchors,
  shouldDeriveSummaryKeyFromAnswerSourceKey,
  startsWithNonPunctuatedWhClauseDeclarative,
  stripLeadingQuestionPromptConjunction,
  stripLeadingTopicPromptConjunction,
  textHasIncompleteLeadingTopicAuthority,
  tokenizeEmbeddedMatchingRunSourceResponse,
  topicPredicateIncludesSubstantiveAnswerContent,
  topicTextMatchesCandidate,
} = createAnswerInterpretationQuestionRuntimeSupport({
  getExtractExplicitTopicSummariesFromQuestionAnswerText: (answer) =>
    extractExplicitTopicSummariesFromQuestionAnswerTextRef?.(answer) ?? [],
  getExtractIncompleteLeadingTopicAuthoritySummariesFromQuestionAnswerText: (answer) =>
    extractIncompleteLeadingTopicAuthoritySummariesFromQuestionAnswerTextRef?.(answer) ?? [],
  getExtractIncompleteLeadingTopicAuthoritySummary: (text) =>
    extractIncompleteLeadingTopicAuthoritySummaryRef?.(text),
  getSubordinateClauseLeadingWords: () => SUBORDINATE_CLAUSE_LEADING_WORDS,
  isStandalonePresentationListMarker,
  matchLeadingSubordinateClauseSequenceLength,
  normalizeExplicitTopicOrQuestionUnitText,
  parsePendingSourceResponseConjunctions,
  parseTopicSourceResponseClauses,
  parseTopicSourceResponseParagraphs,
  parseTopicSourceResponseSentences,
  startsWithMultiTokenSubordinateClauseSequence,
  stripLeadingPresentationListMarkers,
  stripStandalonePresentationListMarkerTokens,
  stripTrailingPresentationListMarkers,
  topicSummaryPrefixPattern: TOPIC_SUMMARY_PREFIX_PATTERN,
  topicSummaryVerbPattern: TOPIC_SUMMARY_VERB_PATTERN,
})

const {
  assertAutoLabeledSectionsDidNotSkipStandaloneQuestionAuthority,
  assertAutoLabeledSectionsDidNotSkipStandaloneTopicAuthority,
  assertDirectInlineTopicsDidNotSkipStandaloneQuestionAuthority,
  assertDirectInlineTopicsDidNotSkipStandaloneTopicAuthority,
  assertDirectLabeledSectionsDidNotSkipStandaloneQuestionAuthority,
  assertDirectLabeledSectionsDidNotSkipStandaloneTopicAuthority,
  assertExplicitLabelTextDoesNotContainAuthority,
  assertLabeledValueAuthorityMatchesLabel,
  assertMatchedAnswerTextAuthorityMatchesConsumer,
  assertSeparatorStyleInlineTopicsDidNotMixWithAdditionalVerbalInlineTopicAuthority,
  assertTextDoesNotContainMalformedStandaloneQuestionSpanAuthority,
  assertTopicAnswerTextDoesNotContainQuestionAuthority,
  autoInlineTopicsShouldYieldIncompleteTopicAuthorityToClauseTopics,
  autoInlineTopicsShouldYieldToExplicitTopicAuthority,
  autoQuestionSurfaceEstablishedExplicitAuthority,
  autoTopicSurfaceEstablishedExplicitAuthority,
  collectSemanticallyValidInlineTopicClauseIndexes,
  extractExplicitTopicSummariesFromQuestionAnswerText,
  extractIncompleteLeadingTopicAuthoritySummariesFromQuestionAnswerText,
  extractIncompleteLeadingTopicAuthoritySummary,
  groupRemainingNonInlineTopicClauseChunks,
  inlineTopicClauseUsesNonLabeledSectionExplicitLabelValueSeparator,
  parseInlineTopicClause,
  parseRequiredInlineTopicSections,
  parseRequiredLabeledSourceResponseSections,
  sourceResponseHasQuestionSentenceAuthority,
  splitInlineTopicClauses,
} = createAnswerInterpretationAuthorityRuntimeSupport({
  assertQuestionAnswerTopicAuthorityMatchesQuestion,
  dedupeNonEmptyStrings,
  extractAsTopicSummary,
  extractCopularTopicSummary,
  extractInferredTopicSummaries,
  extractLeadingTopicSummary,
  extractPrefixedTopicSummary,
  extractQuestionAuthorityTextsFromText,
  extractTopicAnchorCandidateSummariesFromText,
  extractTrailingTopicSummary,
  formatQuotedValueList,
  hasNonPunctuatedWhCommaContinuation,
  inferComparableExplicitLabelSummary,
  isQuestionSourceResponseText,
  matchLeadingSubordinateClauseSequenceLength,
  matchLeadingTopicAuthority,
  normalizeExtractedTopicSummary,
  normalizeExplicitTopicOrQuestionUnitText,
  normalizeQuestionPromptCore,
  normalizeQuestionSourceResponsePrompt,
  parsePendingSourceResponseConjunctions,
  parseTopicSourceResponseClauses,
  parseTopicSourceResponseSentences,
  resolveCanonicalQuestionAnchorMatch,
  startsWithMultiTokenSubordinateClauseSequence,
  startsWithNonPunctuatedWhClauseDeclarative,
  stripLeadingPresentationListMarkers,
  stripLeadingQuestionPromptConjunction,
  stripLeadingTopicPromptConjunction,
  textHasIncompleteLeadingTopicAuthority,
  tokenizeEmbeddedMatchingRunSourceResponse,
  topicPredicateIncludesSubstantiveAnswerContent,
  topicSummaryVerbPattern: TOPIC_SUMMARY_VERB_PATTERN,
  topicTextMatchesCandidate,
})

extractExplicitTopicSummariesFromQuestionAnswerTextRef =
  extractExplicitTopicSummariesFromQuestionAnswerText
extractIncompleteLeadingTopicAuthoritySummariesFromQuestionAnswerTextRef =
  extractIncompleteLeadingTopicAuthoritySummariesFromQuestionAnswerText
extractIncompleteLeadingTopicAuthoritySummaryRef = extractIncompleteLeadingTopicAuthoritySummary

const {
  parseGenericMatchingSourceResponseClauseUnits,
  parseMatchingClosingSourceResponseRuns,
  parseMatchingMiddleSourceResponseRuns,
  parseMatchingOpeningSourceResponseRuns,
  parseMatchingSourceResponseRuns,
} = createAnswerInterpretationMatchingRunSupport({
  findMatchingTopicTextUnitIndexes,
  normalizeEmbeddedMatchingRunText,
  normalizeGenericPendingOrMatchingUnitText,
  parseTopicSourceResponseClauses,
  parseTopicSourceResponseParagraphs,
  parseTopicSourceResponseSentences,
  resolveEmbeddedMatchingRunAnchors,
  tokenizeEmbeddedMatchingRunSourceResponse,
})

const {
  followThroughInfersRemainingAnswers,
  hasMixedRemainingAnswerSourceInference,
  listAutoSourceResponseFormatCandidates,
  listInterpretableFollowThroughAnswerCandidateGroups,
  listInterpretableFollowThroughAnswerSummaries,
  normalizeReservedAnswerCandidateGroups,
  resolveAutoSourceResponseFormat,
  supportsMixedRemainingAnswerSourceInference,
} = createAnswerInterpretationFormatSupport<InterpretablePlanningAnswer>({
  buildPlanningAnswerSourceResponseCandidates,
  extractTrailingTopicSummary,
  parseGenericMatchingSourceResponseClauseUnits,
  parsePendingSourceResponseConjunctions,
  parseTopicSourceResponseSentences,
})

export {
  followThroughInfersRemainingAnswers,
  listAutoSourceResponseFormatCandidates,
  listInterpretableFollowThroughAnswerCandidateGroups,
  listInterpretableFollowThroughAnswerSummaries,
  resolveAutoSourceResponseFormat,
}

const {
  parseRequiredTopicSourceResponseBlocks,
  parseRequiredTopicSourceResponseClauses,
  parseRequiredTopicSourceResponseClosingBlocks,
  parseRequiredTopicSourceResponseClosingSpans,
  parseRequiredTopicSourceResponseMiddleBlocks,
  parseRequiredTopicSourceResponseMiddleSpans,
  parseRequiredTopicSourceResponseParagraphs,
  parseRequiredTopicSourceResponseSentences,
  parseRequiredTopicSourceResponseSpans,
} = createAnswerInterpretationTopicSourceSupport({
  findMatchingNormalizedTopicLabels,
  inferEmbeddedClosingTopicCandidateLabels,
  inferEmbeddedLeadingTopicCandidateLabels,
  inferTopicBlockAnchorLabelsFromParagraph,
  inferTopicClosingBlockLabelsFromParagraph,
  inferTopicClosingSpanLabelsFromSentence,
  inferTopicSpanAnchorLabelsFromSentence,
  normalizeEmbeddedMatchingRunText,
  parsePendingSourceResponseConjunctions,
  parseTopicSourceResponseClauses,
  parseTopicSourceResponseParagraphs,
  parseTopicSourceResponseSentences,
  resolveEmbeddedTopicAnchors,
  resolveSingleTopicAnchorLabel,
  tokenizeEmbeddedMatchingRunSourceResponse,
})

const {
  consumeQuestionBlockSourceResponseMatch,
  consumeQuestionBlockSourceResponseSection,
  consumeQuestionClauseSourceResponseMatch,
  consumeQuestionClauseSourceResponseSection,
  consumeQuestionClosingBlockSourceResponseMatch,
  consumeQuestionClosingBlockSourceResponseSection,
  consumeQuestionClosingSpanSourceResponseMatch,
  consumeQuestionClosingSpanSourceResponseSection,
  consumeQuestionMiddleBlockSourceResponseMatch,
  consumeQuestionMiddleBlockSourceResponseSection,
  consumeQuestionMiddleSpanSourceResponseMatch,
  consumeQuestionMiddleSpanSourceResponseSection,
  consumeQuestionSpanSourceResponseMatch,
  consumeQuestionSpanSourceResponseSection,
  findLabeledSourceResponseSectionEntry,
  markConsumedMatchingIndexes,
  resolveContiguousMatchingIndexes,
} = createAnswerInterpretationSourceResponseSectionSupport({
  findMatchingQuestionBlockIndexes,
  findMatchingQuestionClosingBlockIndexes,
  findMatchingQuestionClosingSpanIndexes,
  findMatchingQuestionSpanIndexes,
  parseRequiredQuestionSourceResponseBlocks,
  parseRequiredQuestionSourceResponseClauses,
  parseRequiredQuestionSourceResponseClosingBlocks,
  parseRequiredQuestionSourceResponseClosingSpans,
  parseRequiredQuestionSourceResponseMiddleBlocks,
  parseRequiredQuestionSourceResponseMiddleSpans,
  parseRequiredQuestionSourceResponseSpans,
})

const {
  findMatchingKnownDecisionsForQuestionBlock,
  findMatchingKnownDecisionsForQuestionClosingBlock,
  findMatchingKnownDecisionsForQuestionClosingSpan,
  findMatchingKnownDecisionsForQuestionSpan,
  findMatchingKnownDecisionsForTopicBlock,
  findMatchingKnownDecisionsForTopicClause,
  findMatchingKnownDecisionsForTopicClosingBlock,
  findMatchingKnownDecisionsForTopicClosingSpan,
  findMatchingKnownDecisionsForTopicParagraph,
  findMatchingKnownDecisionsForTopicSentence,
  findMatchingKnownDecisionsForTopicSpan,
  reserveMatchedLabeledSection,
  reserveMatchedQuestionBlock,
  reserveMatchedQuestionClosingBlock,
  reserveMatchedQuestionClosingSpan,
  reserveMatchedQuestionSpan,
  reserveMatchedTopicBlock,
  reserveMatchedTopicClause,
  reserveMatchedTopicClosingBlock,
  reserveMatchedTopicClosingSpan,
  reserveMatchedTopicParagraph,
  reserveMatchedTopicSentence,
  reserveMatchedTopicSpan,
} = createAnswerInterpretationReservedSourceMatchSupport<InterpretableKnownDecision>({
  buildKnownDecisionSourceResponseCandidates,
  findMatchingQuestionBlockIndexes,
  findMatchingQuestionClosingBlockIndexes,
  findMatchingQuestionClosingSpanIndexes,
  findMatchingQuestionSpanIndexes,
  findMatchingTopicBlockIndexes,
  findMatchingTopicClauseIndexes,
  findMatchingTopicClosingBlockIndexes,
  findMatchingTopicClosingSpanIndexes,
  findMatchingTopicParagraphIndexes,
  findMatchingTopicSentenceIndexes,
  findMatchingTopicSpanIndexes,
  markConsumedMatchingIndexes,
  resolveContiguousMatchingIndexes,
})

const {
  materializePreparedDecisionTopicSurfaceAnswers,
  prepareDecisionTopicSurface,
  reservePreparedDecisionTopicSurfaceCandidates,
} = createAnswerInterpretationDecisionTopicSurfaceSupport<InterpretableKnownDecision>({
  assertLabeledValueAuthorityMatchesLabel,
  assertTopicAnswerTextDoesNotContainQuestionAuthority,
  findMatchingKnownDecisionsForQuestionBlock,
  findMatchingKnownDecisionsForQuestionClosingBlock,
  findMatchingKnownDecisionsForQuestionClosingSpan,
  findMatchingKnownDecisionsForQuestionSpan,
  findMatchingKnownDecisionsForTopicBlock,
  findMatchingKnownDecisionsForTopicClause,
  findMatchingKnownDecisionsForTopicClosingBlock,
  findMatchingKnownDecisionsForTopicClosingSpan,
  findMatchingKnownDecisionsForTopicParagraph,
  findMatchingKnownDecisionsForTopicSentence,
  findMatchingKnownDecisionsForTopicSpan,
  inferSummaryFromQuestionLabel,
  inferTopicSummaryFromTopicBlock,
  inferTopicSummaryFromTopicClosingBlock,
  inferTopicSummaryFromTopicClosingSpan,
  inferTopicSummaryFromTopicParagraph,
  inferTopicSummaryFromTopicSentence,
  inferTopicSummaryFromTopicSpan,
  parseRequiredInlineTopicSections,
  parseRequiredLabeledSourceResponseSections,
  parseRequiredQuestionSourceResponseBlocks,
  parseRequiredQuestionSourceResponseClauses,
  parseRequiredQuestionSourceResponseClosingBlocks,
  parseRequiredQuestionSourceResponseClosingSpans,
  parseRequiredQuestionSourceResponseMiddleBlocks,
  parseRequiredQuestionSourceResponseMiddleSpans,
  parseRequiredQuestionSourceResponseSpans,
  parseRequiredTopicSourceResponseBlocks,
  parseRequiredTopicSourceResponseClauses,
  parseRequiredTopicSourceResponseClosingBlocks,
  parseRequiredTopicSourceResponseClosingSpans,
  parseRequiredTopicSourceResponseMiddleBlocks,
  parseRequiredTopicSourceResponseMiddleSpans,
  parseRequiredTopicSourceResponseParagraphs,
  parseRequiredTopicSourceResponseSentences,
  parseRequiredTopicSourceResponseSpans,
  reserveMatchedLabeledSection,
  reserveMatchedQuestionBlock,
  reserveMatchedQuestionClosingBlock,
  reserveMatchedQuestionClosingSpan,
  reserveMatchedQuestionSpan,
  reserveMatchedTopicBlock,
  reserveMatchedTopicClause,
  reserveMatchedTopicClosingBlock,
  reserveMatchedTopicClosingSpan,
  reserveMatchedTopicParagraph,
  reserveMatchedTopicSentence,
  reserveMatchedTopicSpan,
})

const {
  materializeRemainingPlanningSurfaceAnswers,
  prepareRemainingPlanningSurface,
} = createAnswerInterpretationRemainingPlanningSurfaceSupport({
  assertTopicAnswerTextDoesNotContainQuestionAuthority,
  inferSummaryFromQuestionLabel,
  inferTopicSummaryFromTopicBlock,
  inferTopicSummaryFromTopicClosingBlock,
  inferTopicSummaryFromTopicClosingSpan,
  inferTopicSummaryFromTopicParagraph,
  inferTopicSummaryFromTopicSentence,
  inferTopicSummaryFromTopicSpan,
  parseRequiredQuestionSourceResponseBlocks,
  parseRequiredQuestionSourceResponseClauses,
  parseRequiredQuestionSourceResponseClosingBlocks,
  parseRequiredQuestionSourceResponseClosingSpans,
  parseRequiredQuestionSourceResponseMiddleBlocks,
  parseRequiredQuestionSourceResponseMiddleSpans,
  parseRequiredQuestionSourceResponseSpans,
  parseRequiredTopicSourceResponseBlocks,
  parseRequiredTopicSourceResponseClauses,
  parseRequiredTopicSourceResponseClosingBlocks,
  parseRequiredTopicSourceResponseClosingSpans,
  parseRequiredTopicSourceResponseMiddleBlocks,
  parseRequiredTopicSourceResponseMiddleSpans,
  parseRequiredTopicSourceResponseParagraphs,
  parseRequiredTopicSourceResponseSentences,
  parseRequiredTopicSourceResponseSpans,
})

const {
  consumeTopicBlockSourceResponseSection,
  consumeTopicClauseSourceResponseSection,
  consumeTopicClosingBlockSourceResponseSection,
  consumeTopicClosingSpanSourceResponseSection,
  consumeTopicMiddleBlockSourceResponseSection,
  consumeTopicMiddleSpanSourceResponseSection,
  consumeTopicParagraphSourceResponseSection,
  consumeTopicSentenceSourceResponseSection,
  consumeTopicSpanSourceResponseSection,
} = createAnswerInterpretationTopicSourceResponseSectionSupport({
  assertTopicAnswerTextDoesNotContainQuestionAuthority,
  assertTopicTextHasSubstantiveLeadingAnswerContent,
  extractTopicAnchorCandidateSummariesFromText,
  findMatchingTopicBlockIndexes,
  findMatchingTopicClauseIndexes,
  findMatchingTopicClosingBlockIndexes,
  findMatchingTopicClosingSpanIndexes,
  findMatchingTopicParagraphIndexes,
  findMatchingTopicSentenceIndexes,
  findMatchingTopicSpanIndexes,
  markConsumedMatchingIndexes,
  paragraphTextImpliesMultipleTopicSummaries,
  parseRequiredTopicSourceResponseBlocks,
  parseRequiredTopicSourceResponseClauses,
  parseRequiredTopicSourceResponseClosingBlocks,
  parseRequiredTopicSourceResponseClosingSpans,
  parseRequiredTopicSourceResponseMiddleBlocks,
  parseRequiredTopicSourceResponseMiddleSpans,
  parseRequiredTopicSourceResponseParagraphs,
  parseRequiredTopicSourceResponseSentences,
  parseRequiredTopicSourceResponseSpans,
  registerTopicAnchorCandidates,
  resolveContiguousMatchingIndexes,
})

const {
  orderedBlocksCollapsedMarkedOrderedItems,
  parseRequiredMatchingAnswerSourceEntries,
  parseRequiredOrderedSourceResponseBlocks,
  parseRequiredOrderedSourceResponseItems,
  parseRequiredPendingAnswerSourceEntries,
  parseRequiredPendingSourceResponseClauses,
  parseRequiredPendingSourceResponseConjunctions,
  parseRequiredPendingSourceResponseParagraphs,
  parseRequiredPendingSourceResponseSentences,
  resolveOrderedSourceResponseBlock,
  resolveOrderedSourceResponseItem,
} = createAnswerInterpretationOrderedPendingSourceSupport({
  normalizeExplicitTopicOrQuestionUnitText,
  parseGenericPendingSourceResponseClauses,
  parseGenericPendingSourceResponseParagraphs,
  parseGenericPendingSourceResponseSentences,
  parsePendingSourceResponseConjunctions,
  stripLeadingPresentationListMarkers,
})

const {
  assertAutoDidNotSkipMalformedExplicitInlineTopicAuthority,
  assertAutoPlanningDidNotSkipUnsupportedExplicitLabelAuthority,
  assertAutoSourceResponseFormatCompleteness,
  assertAutoSourceResponseFormatDidNotStopAtWeakerInlineTopics,
  isTerminalLabelFamilyAutoProbeError,
  shouldAutoSourceResponseProbeFailClosed,
} = createAnswerInterpretationAutoProbeSupport({
  assertDirectInlineTopicsDidNotSkipStandaloneQuestionAuthority,
  assertDirectInlineTopicsDidNotSkipStandaloneTopicAuthority,
  assertAutoLabeledSectionsDidNotSkipStandaloneQuestionAuthority,
  assertAutoLabeledSectionsDidNotSkipStandaloneTopicAuthority,
  assertExplicitLabelTextDoesNotContainAuthority,
  assertLabeledValueAuthorityMatchesLabel,
  assertSeparatorStyleInlineTopicsDidNotMixWithAdditionalVerbalInlineTopicAuthority,
  assertTextDoesNotContainMalformedStandaloneQuestionSpanAuthority,
  autoInlineTopicsShouldYieldIncompleteTopicAuthorityToClauseTopics,
  autoInlineTopicsShouldYieldToExplicitTopicAuthority,
  autoQuestionSurfaceEstablishedExplicitAuthority,
  autoTopicSurfaceEstablishedExplicitAuthority,
  collectSemanticallyValidInlineTopicClauseIndexes,
  dedupeNonEmptyStrings,
  extractQuestionAuthorityTextsFromText,
  formatQuotedValueList,
  groupRemainingNonInlineTopicClauseChunks,
  inlineTopicClauseUsesNonLabeledSectionExplicitLabelValueSeparator,
  isQuestionSourceResponseSentence: isQuestionSourceResponseText,
  orderedBlocksCollapsedMarkedOrderedItems,
  parseInlineTopicClause,
  parseMatchingClosingSourceResponseRuns,
  parseMatchingMiddleSourceResponseRuns,
  parseMatchingOpeningSourceResponseRuns,
  parseMatchingSourceResponseRuns,
  parseQuestionSourceResponseClauses,
  parseRequiredInlineTopicSections,
  parseRequiredLabeledSourceResponseSections,
  parseRequiredMatchingAnswerSourceEntries,
  parseRequiredOrderedSourceResponseBlocks,
  parseRequiredOrderedSourceResponseItems,
  parseRequiredPendingAnswerSourceEntries,
  parseRequiredPendingSourceResponseClauses,
  parseRequiredPendingSourceResponseConjunctions,
  parseRequiredPendingSourceResponseParagraphs,
  parseRequiredPendingSourceResponseSentences,
  parseRequiredQuestionSourceResponseBlocks,
  parseRequiredQuestionSourceResponseClauses,
  parseRequiredQuestionSourceResponseClosingBlocks,
  parseRequiredQuestionSourceResponseClosingSpans,
  parseRequiredQuestionSourceResponseMiddleBlocks,
  parseRequiredQuestionSourceResponseMiddleSpans,
  parseRequiredQuestionSourceResponseSpans,
  parseRequiredTopicSourceResponseBlocks,
  parseRequiredTopicSourceResponseClauses,
  parseRequiredTopicSourceResponseClosingBlocks,
  parseRequiredTopicSourceResponseClosingSpans,
  parseRequiredTopicSourceResponseMiddleBlocks,
  parseRequiredTopicSourceResponseMiddleSpans,
  parseRequiredTopicSourceResponseParagraphs,
  parseRequiredTopicSourceResponseSentences,
  parseRequiredTopicSourceResponseSpans,
  resolveCanonicalQuestionAnchorMatch,
  splitInlineTopicClauses,
  sourceResponseHasQuestionSentenceAuthority,
  stripLeadingPresentationListMarkers,
  tokenizeEmbeddedMatchingRunSourceResponse,
})

const {
  materializeRemainingDecisionTopicAnswersFromAnswerSourceEntries,
  resolveRequiredAnswerSourceSummary,
} = createAnswerInterpretationRemainingDecisionAnswerSourceSupport({
  hasMultipleStableMatchHints,
  inferSummaryFromDecisionKey,
  inferSummaryFromStableAnswerSourceKey,
  inferSummaryFromStableMatchHints,
  inferSummaryFromStablePrompt,
  inferSummaryFromStableSummaryKey,
  inferSummaryKeyFromStableAnswerSourceKey,
  shouldDeriveSummaryKeyFromAnswerSourceKey,
})

const {
  consumeSinglePendingSourceResponse,
  materializeMixedRemainingAnswerSourceInference,
  materializeRemainingPlanningAnswerFromAnswerSourceEntry,
  resolveInlineTopicSourceResponseSection,
  resolveLabeledSourceResponseSection,
  resolveMatchingAnswerSourceValue,
  resolveMatchingClosingRunSourceResponseValue,
  resolveMatchingMiddleRunSourceResponseValue,
  resolveMatchingOpeningRunSourceResponseValue,
  resolveMatchingRunSourceResponseValue,
  resolvePendingAnswerSourceValue,
  resolvePendingSourceResponseClause,
  resolvePendingSourceResponseConjunction,
  resolvePendingSourceResponseParagraph,
  resolvePendingSourceResponseSentence,
} = createAnswerInterpretationContentResolutionSupport<
  InterpretableKnownDecision,
  MaterializedInterpretedDecisionAnswer
>({
  assertLabeledValueAuthorityMatchesLabel,
  createInterpretedSourceResponseState,
  findLabeledSourceResponseSectionEntry,
  inferSummaryKeyFromStableAnswerSourceKey,
  materializeRemainingDecisionTopicAnswersFromAnswerSourceEntries,
  normalizeGenericPendingOrMatchingUnitText,
  parseMatchingClosingSourceResponseRuns,
  parseMatchingMiddleSourceResponseRuns,
  parseMatchingOpeningSourceResponseRuns,
  parseMatchingSourceResponseRuns,
  parseRequiredInlineTopicSections,
  parseRequiredLabeledSourceResponseSections,
  parseRequiredMatchingAnswerSourceEntries,
  parseRequiredPendingAnswerSourceEntries,
  parseRequiredPendingSourceResponseClauses,
  parseRequiredPendingSourceResponseConjunctions,
  parseRequiredPendingSourceResponseParagraphs,
  parseRequiredPendingSourceResponseSentences,
  registerMatchingRunCandidateGroups,
  resolveMatchingRunCandidateGroupKey: buildMatchingRunCandidateGroupKey,
  resolveRequiredAnswerSourceSummary,
  shouldDeriveSummaryKeyFromAnswerSourceKey,
  supportsMixedRemainingAnswerSourceInference,
})

const throwSpecificOpenDecisionSurfaceNoMatchError = createOpenDecisionSurfaceNoMatchSupport({
  buildOpenDecisionSourceResponseCandidates,
  consumeQuestionBlockSourceResponseSection,
  consumeQuestionClauseSourceResponseSection,
  consumeQuestionClosingBlockSourceResponseSection,
  consumeQuestionClosingSpanSourceResponseSection,
  consumeQuestionMiddleBlockSourceResponseSection,
  consumeQuestionMiddleSpanSourceResponseSection,
  consumeQuestionSpanSourceResponseSection,
  consumeTopicBlockSourceResponseSection,
  consumeTopicClauseSourceResponseSection,
  consumeTopicClosingBlockSourceResponseSection,
  consumeTopicClosingSpanSourceResponseSection,
  consumeTopicMiddleBlockSourceResponseSection,
  consumeTopicMiddleSpanSourceResponseSection,
  consumeTopicParagraphSourceResponseSection,
  consumeTopicSentenceSourceResponseSection,
  consumeTopicSpanSourceResponseSection,
  getDecisionKey: (decision: InterpretableOpenDecision) => decision.decisionKey,
  resolveMatchingAnswerSourceValue,
  resolveMatchingClosingRunSourceResponseValue,
  resolveMatchingMiddleRunSourceResponseValue,
  resolveMatchingOpeningRunSourceResponseValue,
  resolveMatchingRunSourceResponseValue,
})

const { materializeMatchingOpenDecisionSurfaceAnswers } =
  createAnswerInterpretationOpenDecisionMaterializationSupport<InterpretableOpenDecision>({
    assertLabeledValueAuthorityMatchesLabel,
    assertMatchedAnswerTextAuthorityMatchesConsumer,
    buildDecisionPendingAnswerSourceConsumerDescriptor,
    buildOpenDecisionSourceResponseCandidates,
    consumeQuestionBlockSourceResponseSection,
    consumeQuestionClauseSourceResponseSection,
    consumeQuestionClosingBlockSourceResponseSection,
    consumeQuestionClosingSpanSourceResponseSection,
    consumeQuestionMiddleBlockSourceResponseSection,
    consumeQuestionMiddleSpanSourceResponseSection,
    consumeQuestionSpanSourceResponseSection,
    consumeSinglePendingSourceResponse,
    consumeTopicBlockSourceResponseSection,
    consumeTopicClauseSourceResponseSection,
    consumeTopicClosingBlockSourceResponseSection,
    consumeTopicClosingSpanSourceResponseSection,
    consumeTopicMiddleBlockSourceResponseSection,
    consumeTopicMiddleSpanSourceResponseSection,
    consumeTopicParagraphSourceResponseSection,
    consumeTopicSentenceSourceResponseSection,
    consumeTopicSpanSourceResponseSection,
    findLabeledSourceResponseSectionEntry,
    parseRequiredInlineTopicSections,
    parseRequiredLabeledSourceResponseSections,
    registerMatchingRunCandidateGroups,
    resolveMatchingAnswerSourceValue,
    resolveMatchingClosingRunSourceResponseValue,
    resolveMatchingMiddleRunSourceResponseValue,
    resolveMatchingOpeningRunSourceResponseValue,
    resolveMatchingRunSourceResponseValue,
    resolveOrderedSourceResponseBlock,
    resolveOrderedSourceResponseItem,
    resolvePendingAnswerSourceValue,
    resolvePendingSourceResponseClause,
    resolvePendingSourceResponseConjunction,
    resolvePendingSourceResponseParagraph,
    resolvePendingSourceResponseSentence,
  })

const { resolveAnswerContent: resolveStructuredAnswerContent } =
  createAnswerInterpretationAnswerContentSupport({
    assertMatchedAnswerTextAuthorityMatchesConsumer,
    consumeQuestionBlockSourceResponseMatch,
    consumeQuestionClauseSourceResponseMatch,
    consumeQuestionClosingBlockSourceResponseMatch,
    consumeQuestionClosingSpanSourceResponseMatch,
    consumeQuestionMiddleBlockSourceResponseMatch,
    consumeQuestionMiddleSpanSourceResponseMatch,
    consumeQuestionSpanSourceResponseMatch,
    consumeSinglePendingSourceResponse,
    consumeTopicBlockSourceResponseSection,
    consumeTopicClauseSourceResponseSection,
    consumeTopicClosingBlockSourceResponseSection,
    consumeTopicClosingSpanSourceResponseSection,
    consumeTopicMiddleBlockSourceResponseSection,
    consumeTopicMiddleSpanSourceResponseSection,
    consumeTopicParagraphSourceResponseSection,
    consumeTopicSentenceSourceResponseSection,
    consumeTopicSpanSourceResponseSection,
    resolveInlineTopicSourceResponseSection,
    resolveLabeledSourceResponseSection,
    resolveMatchingAnswerSourceValue,
    resolveMatchingClosingRunSourceResponseValue,
    resolveMatchingMiddleRunSourceResponseValue,
    resolveMatchingOpeningRunSourceResponseValue,
    resolveMatchingRunSourceResponseValue,
    resolveOrderedSourceResponseBlock,
    resolveOrderedSourceResponseItem,
    resolvePendingAnswerSourceValue,
    resolvePendingSourceResponseClause,
    resolvePendingSourceResponseConjunction,
    resolvePendingSourceResponseParagraph,
    resolvePendingSourceResponseSentence,
  })

const {
  assertDirectAnswerSourceFamilySourceResponseCompleteness,
  assertDirectLabelFamilySourceResponseCompleteness,
  assertDirectMatchingRunSourceResponseCompleteness,
  assertDirectOrderedSourceResponseCompleteness,
  assertDirectPendingSourceResponseCompleteness,
  assertDirectQuestionAndTopicSourceResponseCompleteness,
  assertNoUnusedExplicitlyRoutedAnswerSources,
} = createDirectSourceResponseCompletenessSupport({
  parseRequiredLabeledSourceResponseSections,
  parseRequiredInlineTopicSections,
  assertDirectLabeledSectionsDidNotSkipStandaloneQuestionAuthority,
  assertDirectLabeledSectionsDidNotSkipStandaloneTopicAuthority,
  assertDirectInlineTopicsDidNotSkipStandaloneQuestionAuthority,
  assertDirectInlineTopicsDidNotSkipStandaloneTopicAuthority,
  parseQuestionSourceResponseBlocks,
  parseQuestionSourceResponseClauses,
  parseQuestionSourceResponseSpans,
  parseQuestionSourceResponseMiddleSpans,
  parseQuestionSourceResponseClosingSpans,
  parseQuestionSourceResponseClosingBlocks,
  parseQuestionSourceResponseMiddleBlocks,
  parseRequiredTopicSourceResponseClauses,
  parseRequiredTopicSourceResponseSentences,
  parseRequiredTopicSourceResponseSpans,
  parseRequiredTopicSourceResponseMiddleSpans,
  parseRequiredTopicSourceResponseClosingSpans,
  parseRequiredTopicSourceResponseClosingBlocks,
  parseRequiredTopicSourceResponseParagraphs,
  parseRequiredTopicSourceResponseMiddleBlocks,
  parseRequiredTopicSourceResponseBlocks,
  parseRequiredOrderedSourceResponseItems,
  parseRequiredOrderedSourceResponseBlocks,
  parseRequiredPendingSourceResponseClauses,
  parseRequiredPendingSourceResponseParagraphs,
  parseRequiredPendingSourceResponseSentences,
  parseRequiredPendingSourceResponseConjunctions,
  parseRequiredPendingAnswerSourceEntries,
  parseRequiredMatchingAnswerSourceEntries,
  parseMatchingSourceResponseRuns,
  parseMatchingOpeningSourceResponseRuns,
  parseMatchingClosingSourceResponseRuns,
  parseMatchingMiddleSourceResponseRuns,
})

export {
  materializeInterpretedDecisionAnswerBatch,
  materializeInterpretedDecisionAnswers,
  materializeInterpretedDecisionBundle,
  materializeInterpretedDecisionFollowThrough,
  materializeInterpretedPlanningBatchInput,
  materializeInterpretedPlanningInput,
  materializeInterpretedPlanningWorkflowBatchInput,
}

const {
  attachCaptureFormat,
  finalizeMaterializedPlanningAnswers,
  materializeInterpretedDecisionFollowThrough,
  materializeInterpretedPlanningBatchInput,
  materializeInterpretedPlanningInput,
  materializeInterpretedPlanningWorkflowBatchInput,
} = createAnswerInterpretationPlanningMaterializationSupport({
  assertAutoPlanningDidNotSkipUnsupportedExplicitLabelAuthority,
  assertAutoSourceResponseFormatCompleteness: ({
    sourceResponse,
    answerSources,
    sourceResponseFormat,
    sourceResponseState,
  }) =>
    assertAutoSourceResponseFormatCompleteness({
      sourceResponse,
      answerSources,
      sourceResponseFormat,
      sourceResponseState,
    }),
  assertAutoSourceResponseFormatDidNotStopAtWeakerInlineTopics,
  assertDirectAnswerSourceFamilySourceResponseCompleteness,
  assertDirectLabelFamilySourceResponseCompleteness,
  assertDirectMatchingRunSourceResponseCompleteness,
  assertDirectOrderedSourceResponseCompleteness,
  assertDirectPendingSourceResponseCompleteness,
  assertDirectQuestionAndTopicSourceResponseCompleteness,
  assertNoUnusedExplicitlyRoutedAnswerSources,
  buildPlanningAnswerSourceResponseCandidates,
  buildPlanningPendingAnswerSourceConsumerDescriptor,
  createAutoSourceResponseTerminalError: (message) => new AutoSourceResponseTerminalError(message),
  createInterpretedSourceResponseState,
  followThroughInfersRemainingAnswers,
  isTerminalLabelFamilyAutoProbeError,
  listAutoSourceResponseFormatCandidates,
  listInterpretableFollowThroughAnswerCandidateGroups,
  listInterpretableFollowThroughAnswerSummaries,
  materializeRemainingPlanningAnswerFromAnswerSourceEntry,
  materializeRemainingPlanningSurfaceAnswers,
  parseRequiredMatchingAnswerSourceEntries,
  parseRequiredPendingAnswerSourceEntries,
  prepareRemainingPlanningSurface,
  registerMatchingRunCandidateGroups,
  registerQuestionAnchorCandidateGroups,
  registerTopicAnchorCandidates,
  resolveAutoSourceResponseFormat,
  resolveRemainingMatchingPlanningAnswerSourceGroupDescriptor,
  resolveStructuredAnswerContent,
  shouldAutoSourceResponseProbeFailClosed,
})

const {
  materializeInterpretedDecisionAnswerBatch,
  materializeInterpretedDecisionAnswers,
  materializeInterpretedDecisionBundle,
} = createAnswerInterpretationDecisionMaterializationSupport({
  assertAutoDidNotSkipMalformedExplicitInlineTopicAuthority,
  assertAutoSourceResponseFormatCompleteness,
  assertAutoSourceResponseFormatDidNotStopAtWeakerInlineTopics,
  assertDirectAnswerSourceFamilySourceResponseCompleteness,
  assertDirectLabelFamilySourceResponseCompleteness,
  assertDirectMatchingRunSourceResponseCompleteness,
  assertDirectOrderedSourceResponseCompleteness,
  assertDirectPendingSourceResponseCompleteness,
  assertDirectQuestionAndTopicSourceResponseCompleteness,
  assertNoUnusedExplicitlyRoutedAnswerSources,
  attachCaptureFormat,
  buildDecisionAnswerSourceResponseCandidates,
  buildDecisionPendingAnswerSourceConsumerDescriptor,
  buildKnownDecisionSourceResponseCandidates,
  buildOpenDecisionSourceResponseCandidates,
  createAutoSourceResponseTerminalError: (message) => new AutoSourceResponseTerminalError(message),
  createInterpretedSourceResponseState,
  finalizeMaterializedPlanningAnswers,
  followThroughInfersRemainingAnswers,
  hasMixedRemainingAnswerSourceInference,
  isTerminalLabelFamilyAutoProbeError,
  listAutoSourceResponseFormatCandidates,
  listInterpretableFollowThroughAnswerSummaries,
  materializeInterpretedDecisionFollowThrough,
  materializeMatchingOpenDecisionSurfaceAnswers,
  materializeMixedRemainingAnswerSourceInference,
  materializePreparedDecisionTopicSurfaceAnswers,
  materializeRemainingDecisionTopicAnswersFromAnswerSourceEntries,
  normalizeReservedAnswerCandidateGroups,
  parseRequiredInlineTopicSections,
  parseRequiredLabeledSourceResponseSections,
  parseRequiredMatchingAnswerSourceEntries,
  parseRequiredPendingAnswerSourceEntries,
  prepareDecisionTopicSurface,
  registerMatchingRunCandidateGroups,
  registerQuestionAnchorCandidateGroups,
  registerTopicAnchorCandidates,
  reservePreparedDecisionTopicSurfaceCandidates,
  resolveAutoSourceResponseFormat,
  resolveRemainingMatchingDecisionAnswerSourceGroupDescriptor,
  resolveStructuredAnswerContent,
  shouldAutoSourceResponseProbeFailClosed,
  supportsMixedRemainingAnswerSourceInference,
  throwSpecificOpenDecisionSurfaceNoMatchError,
})
