export const SUBORDINATE_CLAUSE_LEADING_TOKEN_SEQUENCES = [
  ['any', 'time'],
  ['as', 'far', 'as'],
  ['as', 'long', 'as'],
  ['as', 'much', 'as'],
  ['as', 'soon', 'as'],
  ['as', 'if'],
  ['as', 'though'],
  ['again', 'and', 'again'],
  ['all', 'along'],
  ['all', 'at', 'once'],
  ['all', 'of', 'a', 'sudden'],
  ['all', 'the', 'while'],
  ['all', 'this', 'time'],
  ['all', 'too', 'often'],
  ['at', 'another', 'point'],
  ['at', 'an', 'early', 'stage'],
  ['at', 'first'],
  ['at', 'intervals'],
  ['at', 'irregular', 'intervals'],
  ['at', 'last'],
  ['at', 'length'],
  ['at', 'present'],
  ['at', 'regular', 'intervals'],
  ['at', 'some', 'stage'],
  ['at', 'that', 'point'],
  ['at', 'that', 'stage'],
  ['at', 'the', 'outset'],
  ['at', 'this', 'point'],
  ['at', 'this', 'stage'],
  ['even', 'as'],
  ['even', 'if'],
  ['even', 'when'],
  ['even', 'though'],
  ['except', 'if'],
  ['except', 'when'],
  ['at', 'one', 'point'],
  ['at', 'some', 'point'],
  ['at', 'times'],
  ['by', 'the', 'time'],
  ['each', 'time'],
  ['every', 'time'],
  ['every', 'now', 'and', 'again'],
  ['every', 'now', 'and', 'then'],
  ['every', 'blue', 'moon'],
  ['every', 'once', 'in', 'a', 'while'],
  ['every', 'so', 'often'],
  ['fear', 'that'],
  ['fifth', 'time'],
  ['first', 'time'],
  ['fourth', 'time'],
  ['for', 'fear', 'that'],
  ['for', 'a', 'while'],
  ['for', 'the', 'foreseeable', 'future'],
  ['for', 'the', 'near', 'future'],
  ['for', 'now'],
  ['for', 'quite', 'a', 'while'],
  ['for', 'the', 'time', 'being'],
  ['from', 'time', 'immemorial'],
  ['from', 'time', 'to', 'time'],
  ['given', 'that'],
  ['independent', 'of', 'whether'],
  ['in', 'case'],
  ['in', 'due', 'course'],
  ['in', 'the', 'meantime'],
  ['inasmuch', 'as'],
  ['in', 'order', 'to'],
  ['insofar', 'as'],
  ['irrespective', 'of', 'whether'],
  ['just', 'as'],
  ['last', 'time'],
  ['now', 'and', 'again'],
  ['now', 'and', 'then'],
  ['next', 'time'],
  ['not', 'infrequently'],
  ['second', 'time'],
  ['third', 'time'],
  ['the', 'first', 'time'],
  ['the', 'fifth', 'time'],
  ['the', 'fourth', 'time'],
  ['the', 'instant'],
  ['the', 'last', 'time'],
  ['the', 'minute'],
  ['the', 'moment'],
  ['the', 'next', 'time'],
  ['the', 'ninth', 'time'],
  ['the', 'second', 'time'],
  ['the', 'seventh', 'time'],
  ['the', 'sixth', 'time'],
  ['the', 'tenth', 'time'],
  ['the', 'third', 'time'],
  ['the', 'eighth', 'time'],
  ['now', 'that'],
  ['no', 'matter', 'how'],
  ['no', 'matter', 'if'],
  ['no', 'matter', 'when'],
  ['no', 'matter', 'whether'],
  ['once', 'again'],
  ['once', 'in', 'a', 'blue', 'moon'],
  ['only', 'if'],
  ['only', 'when'],
  ['off', 'and', 'on'],
  ['on', 'and', 'off'],
  ['on', 'a', 'daily', 'basis'],
  ['on', 'a', 'monthly', 'basis'],
  ['on', 'a', 'regular', 'basis'],
  ['on', 'a', 'weekly', 'basis'],
  ['on', 'a', 'yearly', 'basis'],
  ['on', 'an', 'irregular', 'basis'],
  ['on', 'occasion'],
  ['on', 'rare', 'occasions'],
  ['on', 'short', 'notice'],
  ['once', 'in', 'a', 'while'],
  ['over', 'and', 'over'],
  ['over', 'and', 'over', 'again'],
  ['provided', 'that'],
  ['regardless', 'of', 'whether'],
  ['save', 'that'],
  ['seeing', 'that'],
  ['so', 'long', 'as'],
  ['so', 'far', 'as'],
  ['so', 'often'],
  ['so', 'that'],
  ['sooner', 'or', 'later'],
  ['supposing', 'that'],
  ['more', 'often', 'than', 'not'],
  ['time', 'after', 'time'],
  ['time', 'and', 'again'],
  ['time', 'and', 'time', 'again'],
  ['to', 'date'],
  ['to', 'this', 'day'],
  ['until', 'then'],
  ['after', 'a', 'while'],
  ['after', 'a', 'time'],
  ['after', 'some', 'time'],
  ['after'],
  ['afterward'],
  ['afterwards'],
  ['accordingly'],
  ['admittedly'],
  ['although'],
  ['alternatively'],
  ['another', 'time'],
  ['apparently'],
  ['arguably'],
  ['assuming'],
  ['at', 'irregular', 'times'],
  ['at', 'regular', 'times'],
  ['at', 'short', 'notice'],
  ['back', 'and', 'forth'],
  ['before', 'too', 'long'],
  ['because'],
  ['before', 'long'],
  ['before'],
  ['beforehand'],
  ['basically'],
  ['by', 'then'],
  ['broadly'],
  ['certainly'],
  ['chiefly'],
  ['conceivably'],
  ['concurrently'],
  ['collectively'],
  ['consequently'],
  ['crucially'],
  ['conventionally'],
  ['conversely'],
  ['currently'],
  ['day', 'after', 'day'],
  ['day', 'by', 'day'],
  ['decidedly'],
  ['definitely'],
  ['earlier'],
  ['effectively'],
  ['essentially'],
  ['evidently'],
  ['ever', 'since'],
  ['finally'],
  ['formally'],
  ['for', 'a', 'time'],
  ['for', 'the', 'first', 'little', 'while'],
  ['for', 'the', 'next', 'little', 'while'],
  ['formerly'],
  ['granted'],
  ['for', 'some', 'time'],
  ['from', 'day', 'one'],
  ['from', 'now', 'on'],
  ['from', 'the', 'beginning'],
  ['from', 'the', 'outset'],
  ['from', 'that', 'point', 'on'],
  ['from', 'then', 'on'],
  ['from', 'this', 'point', 'on'],
  ['fundamentally'],
  ['given'],
  ['gradually'],
  ['generally'],
  ['hence'],
  ['henceforth'],
  ['henceforward'],
  ['hereafter'],
  ['hereby'],
  ['hereupon'],
  ['historically'],
  ['if'],
  ['ideally'],
  ['immediately'],
  ['implicitly'],
  ['importantly'],
  ['incidentally'],
  ['individually'],
  ['initially'],
  ['informally'],
  ['instantly'],
  ['instead'],
  ['inevitably'],
  ['lately'],
  ['lest'],
  ['later'],
  ['largely'],
  ['in', 'the', 'early', 'stages'],
  ['loosely'],
  ['in', 'no', 'time'],
  ['in', 'the', 'foreseeable', 'future'],
  ['in', 'the', 'fullness', 'of', 'time'],
  ['in', 'the', 'later', 'stages'],
  ['in', 'short', 'order'],
  ['in', 'the', 'beginning'],
  ['in', 'the', 'end'],
  ['in', 'the', 'long', 'run'],
  ['in', 'the', 'long', 'term'],
  ['in', 'the', 'medium', 'term'],
  ['in', 'the', 'near', 'term'],
  ['in', 'the', 'near', 'future'],
  ['in', 'the', 'short', 'run'],
  ['in', 'the', 'short', 'term'],
  ['in', 'time'],
  ['instant'],
  ['little', 'by', 'little'],
  ['meanwhile'],
  ['mainly'],
  ['manifestly'],
  ['merely'],
  ['minute'],
  ['moment'],
  ['momentarily'],
  ['month', 'after', 'month'],
  ['naturally'],
  ['ninth', 'time'],
  ['night', 'after', 'night'],
  ['normally'],
  ['nowadays'],
  ['notably'],
  ['occasionally'],
  ['officially'],
  ['ordinarily'],
  ['ostensibly'],
  ['otherwise'],
  ['over', 'time'],
  ['nominally'],
  ['narrowly'],
  ['partially'],
  ['partly'],
  ['permanently'],
  ['possibly'],
  ['practically'],
  ['predominantly'],
  ['provided'],
  ['presently'],
  ['previously'],
  ['primarily'],
  ['promptly'],
  ['provisionally'],
  ['potentially'],
  ['presumably'],
  ['principally'],
  ['approximately'],
  ['save'],
  ['realistically'],
  ['regularly'],
  ['recently'],
  ['remarkably'],
  ['roughly'],
  ['seemingly'],
  ['simply'],
  ['similarly'],
  ['simultaneously'],
  ['seventh', 'time'],
  ['seeing'],
  ['since', 'then'],
  ['since'],
  ['sixth', 'time'],
  ['soon'],
  ['shortly'],
  ['sometimes'],
  ['specifically'],
  ['step', 'by', 'step'],
  ['strictly'],
  ['subsequently'],
  ['supposing'],
  ['surely'],
  ['tentatively'],
  ['thereafter'],
  ['thereupon'],
  ['that', 'time'],
  ['tenth', 'time'],
  ['temporarily'],
  ['this', 'time'],
  ['theoretically'],
  ['technically'],
  ['though'],
  ['traditionally'],
  ['typically'],
  ['thereby'],
  ['therefore'],
  ['ultimately'],
  ['undoubtedly'],
  ['usually'],
  ['thus'],
  ['virtually'],
  ['eventually'],
  ['explicitly'],
  ['academically'],
  ['aesthetically'],
  ['administratively'],
  ['allegedly'],
  ['algorithmically'],
  ['analytically'],
  ['alarmingly'],
  ['amazingly'],
  ['abstractly'],
  ['architecturally'],
  ['astonishingly'],
  ['automatically'],
  ['abruptly'],
  ['biologically'],
  ['bizarrely'],
  ['briefly'],
  ['carefully'],
  ['canonically'],
  ['clearly'],
  ['civically'],
  ['chronologically'],
  ['clinically'],
  ['commonly'],
  ['commercially'],
  ['comparatively'],
  ['computationally'],
  ['concretely'],
  ['coincidentally'],
  ['conceptually'],
  ['conveniently'],
  ['confidentially'],
  ['constitutionally'],
  ['contextually'],
  ['counterintuitively'],
  ['contractually'],
  ['critically'],
  ['curiously'],
  ['cynically'],
  ['demographically'],
  ['descriptively'],
  ['diagnostically'],
  ['domestically'],
  ['dramatically'],
  ['culturally'],
  ['delicately'],
  ['deliberately'],
  ['directly'],
  ['ecologically'],
  ['economically'],
  ['empirically'],
  ['ethically'],
  ['environmentally'],
  ['exactly'],
  ['expectedly'],
  ['experimentally'],
  ['externally'],
  ['financially'],
  ['figuratively'],
  ['famously'],
  ['fortunately'],
  ['frankly'],
  ['frequently'],
  ['functionally'],
  ['geographically'],
  ['geologically'],
  ['globally'],
  ['grammatically'],
  ['happily'],
  ['hermeneutically'],
  ['honestly'],
  ['iconically'],
  ['ideologically'],
  ['indirectly'],
  ['industrially'],
  ['institutionally'],
  ['incredibly'],
  ['inexplicably'],
  ['internationally'],
  ['internally'],
  ['interestingly'],
  ['intentionally'],
  ['intuitively'],
  ['ironically'],
  ['juridically'],
  ['judicially'],
  ['legally'],
  ['likewise'],
  ['literally'],
  ['literarily'],
  ['linguistically'],
  ['locally'],
  ['logistically'],
  ['loudly'],
  ['managerially'],
  ['mathematically'],
  ['mechanically'],
  ['mechanistically'],
  ['maybe'],
  ['mercifully'],
  ['medically'],
  ['metaphorically'],
  ['methodologically'],
  ['musically'],
  ['mysteriously'],
  ['narratively'],
  ['notionally'],
  ['notoriously'],
  ['normatively'],
  ['numerically'],
  ['objectively'],
  ['oddly'],
  ['openly'],
  ['operationally'],
  ['organizationally'],
  ['perhaps'],
  ['paradoxically'],
  ['pedagogically'],
  ['personally'],
  ['philosophically'],
  ['physically'],
  ['plainly'],
  ['politely'],
  ['pragmatically'],
  ['prescriptively'],
  ['precisely'],
  ['puzzlingly'],
  ['probabilistically'],
  ['originally'],
  ['predictably'],
  ['privately'],
  ['politically'],
  ['procedurally'],
  ['professionally'],
  ['psychologically'],
  ['publicly'],
  ['purposely'],
  ['quietly'],
  ['qualitatively'],
  ['quantitatively'],
  ['rarely'],
  ['readily'],
  ['regionally'],
  ['regrettably'],
  ['reportedly'],
  ['respectfully'],
  ['rhetorically'],
  ['routinely'],
  ['sadly'],
  ['scientifically'],
  ['secretly'],
  ['semantically'],
  ['seriously'],
  ['shockingly'],
  ['socially'],
  ['sociologically'],
  ['speculatively'],
  ['surprisingly'],
  ['statistically'],
  ['stylistically'],
  ['structurally'],
  ['strategically'],
  ['strangely'],
  ['supposedly'],
  ['suddenly'],
  ['swiftly'],
  ['sympathetically'],
  ['symbolically'],
  ['systematically'],
  ['sharply'],
  ['slowly'],
  ['tactically'],
  ['technologically'],
  ['thankfully'],
  ['thematically'],
  ['textually'],
  ['topologically'],
  ['tragically'],
  ['typologically'],
  ['unexpectedly'],
  ['unfortunately'],
  ['understandably'],
  ['unbelievably'],
  ['unsurprisingly'],
  ['unusually'],
  ['verbally'],
  ['viscerally'],
  ['visibly'],
  ['visually'],
  ['wonderfully'],
  ['week', 'after', 'week'],
  ['with', 'time'],
  ['until'],
  ['unless'],
  ['eighth', 'time'],
  ['whenever'],
  ['whether', 'or', 'not'],
  ['whether'],
  ['whereas'],
  ['wherever'],
  ['while'],
  ['wisely'],
  ['customarily'],
  ['morally'],
  ['year', 'after', 'year'],
] as const

export const SUBORDINATE_CLAUSE_LEADING_WORDS = new Set([
  ...SUBORDINATE_CLAUSE_LEADING_TOKEN_SEQUENCES.flatMap((sequence) =>
    sequence.length === 1 ? [sequence[0]] : [],
  ),
  'once',
  'twice',
  'thrice',
])

export const MULTI_TOKEN_SUBORDINATE_CLAUSE_LEADING_TOKEN_SEQUENCES =
  SUBORDINATE_CLAUSE_LEADING_TOKEN_SEQUENCES.filter((sequence) => sequence.length > 1)

export const SUBORDINATE_CLAUSE_ORDINAL_TIME_SINGLE_TOKEN_ORDINALS = new Set([
  'first',
  'second',
  'third',
  'fourth',
  'fifth',
  'sixth',
  'seventh',
  'eighth',
  'ninth',
  'tenth',
  'eleventh',
  'twelfth',
  'thirteenth',
  'fourteenth',
  'fifteenth',
  'sixteenth',
  'seventeenth',
  'eighteenth',
  'nineteenth',
  'twentieth',
  'thirtieth',
  'fortieth',
  'fiftieth',
  'sixtieth',
  'seventieth',
  'eightieth',
  'ninetieth',
  'hundredth',
])

export const SUBORDINATE_CLAUSE_ORDINAL_TIME_TENS_TOKENS = new Set([
  'twenty',
  'thirty',
  'forty',
  'fifty',
  'sixty',
  'seventy',
  'eighty',
  'ninety',
])

export const SUBORDINATE_CLAUSE_ORDINAL_TIME_COMPOUND_TAIL_TOKENS = new Set([
  'first',
  'second',
  'third',
  'fourth',
  'fifth',
  'sixth',
  'seventh',
  'eighth',
  'ninth',
])

export const SUBORDINATE_CLAUSE_TIME_LEADING_SIMPLE_HEAD_TOKENS = new Set([
  'another',
  'any',
  'each',
  'every',
  'last',
  'many',
  'most',
  'next',
  'one',
  'only',
  'other',
  'same',
  'several',
  'some',
  'that',
  'this',
])

export const SUBORDINATE_CLAUSE_TIME_LEADING_OPTIONAL_PREFIX_TOKENS = new Set(['very', 'yet'])

export const SUBORDINATE_CLAUSE_TIME_LEADING_OPTIONAL_MIDDLE_TOKENS = new Set([
  'couple',
  'every',
  'few',
  'more',
  'other',
  'several',
  'single',
])

export const SUBORDINATE_CLAUSE_TIME_PLURAL_QUANTITY_TOKENS = new Set(['couple', 'few', 'several'])

export const SUBORDINATE_CLAUSE_TIME_DIRECT_TIMES_COUNT_HEAD_TOKENS = new Set([
  'countless',
  'half',
  'multiple',
  'numerous',
])

export const SUBORDINATE_CLAUSE_TIME_LEXICAL_COUNT_HEAD_TOKENS = new Set(['once', 'twice', 'thrice'])

export const SUBORDINATE_CLAUSE_TIME_COUNT_NOUN_LEADING_QUANTIFIER_TOKENS = new Set([
  'few',
  'many',
  'several',
])

export const SUBORDINATE_CLAUSE_TIME_SINGLE_TOKEN_CARDINAL_TOKENS = new Set([
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
  'sixteen',
  'seventeen',
  'eighteen',
  'nineteen',
  'twenty',
  'thirty',
  'forty',
  'fifty',
  'sixty',
  'seventy',
  'eighty',
  'ninety',
])

export const SUBORDINATE_CLAUSE_TIME_COMPOUND_CARDINAL_TENS_TOKENS = new Set([
  'twenty',
  'thirty',
  'forty',
  'fifty',
  'sixty',
  'seventy',
  'eighty',
  'ninety',
])

export const SUBORDINATE_CLAUSE_TIME_COMPOUND_CARDINAL_TAIL_TOKENS = new Set([
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
])

export const SUBORDINATE_CLAUSE_TIME_SINGULAR_COUNT_NOUN_TOKENS = new Set([
  'score',
  'dozen',
  'hundred',
  'thousand',
])

export const SUBORDINATE_CLAUSE_TIME_PLURAL_COUNT_NOUN_TOKENS = new Set([
  'scores',
  'dozens',
  'hundreds',
  'thousands',
])

export const SUBORDINATE_CLAUSE_TIME_DIRECT_THE_TIME_HEAD_TOKENS = new Set(['all', 'half'])

export const SUBORDINATE_CLAUSE_TIME_OF_THE_TIME_HEAD_TOKENS = new Set([
  'all',
  'half',
  'most',
  'much',
  'part',
  'rest',
  'some',
])

export const SUBORDINATE_CLAUSE_TIME_OF_TIMES_HEAD_TOKENS = new Set(['plenty'])

export const SUBORDINATE_CLAUSE_TIME_ARTICLE_LED_OPTIONAL_MODIFIER_TOKENS = new Set([
  'awful',
  'fair',
  'good',
  'great',
  'half',
  'huge',
  'large',
  'small',
  'tiny',
  'very',
  'whole',
])

export const SUBORDINATE_CLAUSE_TIME_PRE_ARTICLE_PREFIX_TOKENS = new Set(['just', 'only', 'quite'])

export const SUBORDINATE_CLAUSE_TIME_ARTICLE_LED_DIRECT_TIMES_HEAD_TOKENS = new Set([
  'couple',
  'few',
  'many',
])

export const SUBORDINATE_CLAUSE_TIME_ARTICLE_LED_COUNT_NOUN_LEADING_HEAD_TOKENS = new Set([
  'couple',
  'few',
])

export const SUBORDINATE_CLAUSE_TIME_ARTICLE_LED_OPTIONAL_POST_HEAD_TOKENS = new Set(['more'])

export const SUBORDINATE_CLAUSE_TIME_RANGE_OR_APPROXIMATION_TAIL_TOKENS = new Set(['more', 'so'])

export const SUBORDINATE_CLAUSE_TIME_ARTICLE_LED_OF_TIMES_HEAD_TOKENS = new Set([
  'bunch',
  'couple',
  'handful',
  'lot',
  'number',
])

export const SUBORDINATE_CLAUSE_TIME_BARE_OF_TIMES_HEAD_TOKENS = new Set([
  'bunch',
  'couple',
  'handful',
  'lot',
  'number',
])

export const SUBORDINATE_CLAUSE_PREPOSITIONAL_TIME_LEADING_TOKENS = new Set(['at', 'by', 'for', 'from'])

export const SUBORDINATE_CLAUSE_PREPOSITIONAL_TIME_POINT_HEAD_TOKENS = new Set([
  'instant',
  'minute',
  'moment',
])

export const SUBORDINATE_CLAUSE_TIME_DURATION_UNIT_TOKENS = new Set([
  'ages',
  'centuries',
  'days',
  'decades',
  'months',
  'weeks',
  'years',
])

export const SUBORDINATE_CLAUSE_TIME_DURATION_HORIZON_MODIFIER_TOKENS = new Set([
  'long',
  'medium',
  'short',
])

